### ISSUE TITLE
Using strikethrough in headers causes rendering error

### ISSUE THREAD

**Issue by dkoga4116** [mikewudev/marks-nav#2]
Hi, I enjoy your plugin on Inkdrop.
 
I see an error when I use strikethrough(~~ ~~) in headers.
When I do that with marks-nav on, the app seems unable to render markdown.
The app renders normally when I use strikethrough in normal paragraphs.
 
Thank you.

**Comment by mikewuu** [comment]
Thanks GitCats!! Happy to hear somebody else found it useful 🙂 , and thanks for reporting. Will look into it.

**Comment by mikewuu** [comment]
@GitCats-061 tried to replicate this, but it seems to work ok with strikethrough here, could you please provide more details:

- Inkdrop version
- Error (see console)
- Screenshot

![image](https://user-images.githubusercontent.com/11449462/102784689-13de4080-43e0-11eb-9244-2117ffbe7603.png)

**Comment by dkoga4116** [comment]
Hi, I'll send some more information.

My Inkdrop version is 5.2.0.

Here are screenshots, with marks-nav on or off.
![image](https://user-images.githubusercontent.com/59495041/102837908-3e5fe600-4440-11eb-8ab0-5be0eaacbef2.png)
![image](https://user-images.githubusercontent.com/59495041/102838023-8121be00-4440-11eb-9e24-43cd74a877c0.png)

And here is the error message.

/Applications/Inkdro…g/src/common.js:114 app:error Failed to render preview: +22s TypeError: Cannot read property 'toLowerCase' of undefined

I hope this helps.

**Comment by mikewuu** [comment]
Thanks @GitCats-061 , unfortunately I'm not calling `toLowerCase` in any of the code. Could you please try disabling all other plugins, and seeing if it works?

**Comment by dkoga4116** [comment]
Hi. 
I just tried disabling all other plugins as you said, but the result is the same...

**Comment by dkoga4116** [comment]
Is it possible that there is a conflict between the plugin and a app theme or something ?

**Comment by mikewuu** [comment]
Thanks, that's very possible. I'm running 5.2.0 as well on default theme.

**Comment by dkoga4116** [comment]
I changed all my theme or syntax to default ones, but still there's the issue. 
Now, I should think about my mac is conflicting with the plugin...

**Comment by mikewuu** [comment]
Sorry GitCats, I've tried it on a fresh install and still don't see the issue you're describing. Going to close this issue until it can be replicated.
